services:
  - type: web
    name: n8n-academia-gratis
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_USER_MANAGEMENT_JWT_SECRET
        generateValue: true
